apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: node-nodevfile-nodocker-rhtap-three-component-scenarios-4amz
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: node-nodevfile-nodocker-rhtap-three-component-scenarios-4amz
    app.kubernetes.io/part-of: mc-three-scenarios
  name: node-nodevfile-nodocker-rhtap-three-component-scenarios-4amz
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: node-nodevfile-nodocker-rhtap-three-component-scenarios-4amz
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: node-nodevfile-nodocker-rhtap-three-component-scenarios-4amz
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-ulou-tenant/mc-three-scenarios/node-nodevfile-nodocker-rhtap-three-component-scenarios-4amz@sha256:41c5c25bc4a3f46f75de01e7e4b905cde0d3ca6823ff666d99e18254bad7245c
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
