apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-go-rhtap-three-component-scenarios-rc5a
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-ulou-tenant/mc-three-scenarios/devfile-go-rhtap-three-component-scenarios-rc5a@sha256:b7fcd46269457b8d2328f93b63168dcfb786b8adcdbc6186d919760866251a62
        name: my-go
        resources: {}
status: {}
